Graphql
1Like1Prayer/amaRomach-server pull request #3
Opened 2021-06-03 06:49 UTC by 1Like1Prayer

2021-06-03 13:07 UTC, rongoldinfeld requested changes

2021-06-03 13:07 UTC, rongoldinfeld commented on src/graphql/resolvers/product-resolver.ts
> +        return await ProductModel.findById(value);
what if the product doesnt exists?

2021-06-03 13:07 UTC, rongoldinfeld commented on src/graphql/resolvers/product-resolver.ts
> +                throw new UserInputError(
this error is thrown if amount is bigger than stock, or when the product id doesnt exists

2021-06-03 13:07 UTC, rongoldinfeld commented on src/graphql/resolvers/product-resolver.ts
> +              const product = await ProductModel.findOne({ _id: cartProduct.id }).session(session);
extract specificProductCheckout to a function for readability

2021-06-05 13:54 UTC, 1Like1Prayer commented on src/graphql/resolvers/product-resolver.ts
> +      const { error: err, value: productId } = joiIdSchema.validate(id);
you should no be able to change product id(that is given by mongo). if I'll merge both validation schemas  it'll mean that I'll be able to send the "id" property in `product changes` which I don't want to allow.

2021-07-01 10:58 UTC, rongoldinfeld requested changes

2021-07-01 10:58 UTC, rongoldinfeld commented on src/graphql/graphql-server.ts
> +      return new ApolloError('Internal Error');
log the full error

2021-07-01 10:58 UTC, rongoldinfeld commented on src/graphql/resolvers/product-resolver.ts
> +    addProductToCart: (_: any, { id, amount }: any, context: any) => {
fix context any type

2021-07-01 10:58 UTC, rongoldinfeld commented on src/graphql/resolvers/product-resolver.ts
> +        throw new UserInputError(error.message);
more like a bad request then user input error

2021-07-01 10:58 UTC, rongoldinfeld commented on src/graphql/resolvers/product-resolver.ts
> +      pubsub.publish('PRODUCT_ADDED', { product: [{ id: productId, amount: 1 }] });
`PRODUCT_ADDED` is the same event as `PRODUCT_CHANGED`

2021-07-01 10:58 UTC, rongoldinfeld commented on src/graphql/resolvers/product-resolver.ts
> +      pubsub.publish('PRODUCT_ADDED', { product: [{ id: productId, amount: 1 }] });
product should be products

2021-07-01 10:58 UTC, rongoldinfeld commented on src/graphql/resolvers/product-resolver.ts
> +      return product ? true : false;
in case the product does not exists throw an error

2021-07-01 10:58 UTC, rongoldinfeld commented on src/graphql/resolvers/product-resolver.ts
> +    connectionQuery: (_: any, __: any, Context: any) => {
you can remove it, when a user adds to cart you will create a key in the resolver

2021-07-01 10:58 UTC, rongoldinfeld commented on src/graphql/resolvers/product-resolver.ts
> +const checkoutProduct = async (
fits a helper file

2021-07-01 10:58 UTC, rongoldinfeld commented on src/graphql/schemas/product-schema.ts
> +    connectionQuery: Boolean
remove

2021-07-01 10:58 UTC, rongoldinfeld commented on src/graphql/resolvers/product-resolver.ts
> +import { ApolloError, PubSub, UserInputError } from 'apollo-server';
all of your reservation actions do not validate existence of a user/product,
validate it and throw errors accordingly

2021-07-06 12:52 UTC, rongoldinfeld approved these changes

2021-07-06 12:55 UTC, merged